import { DatabaseSync } from "node:sqlite";
const schemas = [
  "CREATE TABLE IF NOT EXISTS life_events (\n        id TEXT PRIMARY KEY NOT NULL,\n        title TEXT NOT NULL DEFAULT '',\n        content TEXT NOT NULL DEFAULT '',\n        kind TEXT NOT NULL DEFAULT '\u751f\u6d3b',\n        mood TEXT NOT NULL DEFAULT '\u5e73\u9759',\n        energy INTEGER NOT NULL DEFAULT 3,\n        tags TEXT NOT NULL DEFAULT '[]',\n        person TEXT NOT NULL DEFAULT '',\n        place TEXT NOT NULL DEFAULT '',\n        project TEXT NOT NULL DEFAULT '',\n        is_private INTEGER NOT NULL DEFAULT 0,\n        record_status TEXT NOT NULL DEFAULT 'published',\n        revision INTEGER NOT NULL DEFAULT 1,\n        happened_at TEXT NOT NULL,\n        created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,\n        updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,\n        deleted_at TEXT\n      )",
  "CREATE TABLE IF NOT EXISTS audit_logs (\n        id TEXT PRIMARY KEY NOT NULL,\n        action TEXT NOT NULL,\n        entity_type TEXT NOT NULL,\n        entity_id TEXT NOT NULL DEFAULT '',\n        device_id TEXT NOT NULL DEFAULT '',\n        detail_json TEXT NOT NULL DEFAULT '{}',\n        created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP\n      )",
  "CREATE TABLE IF NOT EXISTS schedule_events (\n        id TEXT PRIMARY KEY NOT NULL,\n        title TEXT NOT NULL,\n        category TEXT NOT NULL DEFAULT '\u5b66\u4e60',\n        start_at TEXT NOT NULL,\n        end_at TEXT NOT NULL,\n        place TEXT NOT NULL DEFAULT '',\n        person TEXT NOT NULL DEFAULT '',\n        project TEXT NOT NULL DEFAULT '',\n        note TEXT NOT NULL DEFAULT '',\n        repeat_rule TEXT NOT NULL DEFAULT '\u4e0d\u91cd\u590d',\n        status TEXT NOT NULL DEFAULT '\u8ba1\u5212\u4e2d',\n        planned_minutes INTEGER NOT NULL DEFAULT 0,\n        actual_minutes INTEGER NOT NULL DEFAULT 0,\n        created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP\n      )",
  "CREATE TABLE IF NOT EXISTS inbox_items (\n        id TEXT PRIMARY KEY NOT NULL,\n        content TEXT NOT NULL,\n        source_type TEXT NOT NULL DEFAULT '\u6587\u5b57',\n        status TEXT NOT NULL DEFAULT '\u5f85\u6574\u7406',\n        created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP\n      )",
  "CREATE TABLE IF NOT EXISTS schedule_rule_settings (\n        schedule_id TEXT PRIMARY KEY NOT NULL,\n        repeat_until TEXT,\n        reminder_minutes INTEGER NOT NULL DEFAULT 10,\n        custom_interval INTEGER NOT NULL DEFAULT 1,\n        custom_unit TEXT NOT NULL DEFAULT 'week',\n        weekdays TEXT NOT NULL DEFAULT '[]',\n        created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,\n        updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,\n        FOREIGN KEY (schedule_id) REFERENCES schedule_events(id) ON DELETE CASCADE\n      )",
  "CREATE TABLE IF NOT EXISTS schedule_instances (\n        id TEXT PRIMARY KEY NOT NULL,\n        schedule_id TEXT NOT NULL,\n        occurrence_start TEXT NOT NULL,\n        occurrence_end TEXT NOT NULL,\n        status TEXT NOT NULL DEFAULT '\u8ba1\u5212\u4e2d',\n        actual_minutes INTEGER NOT NULL DEFAULT 0,\n        actual_start_at TEXT,\n        actual_end_at TEXT,\n        interruption_reason TEXT NOT NULL DEFAULT '',\n        reflection TEXT NOT NULL DEFAULT '',\n        created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,\n        updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,\n        FOREIGN KEY (schedule_id) REFERENCES schedule_events(id) ON DELETE CASCADE,\n        UNIQUE(schedule_id, occurrence_start)\n      )",
  "CREATE TABLE IF NOT EXISTS schedule_exceptions (\n        id TEXT PRIMARY KEY NOT NULL,\n        schedule_id TEXT NOT NULL,\n        occurrence_start TEXT NOT NULL,\n        reason TEXT NOT NULL DEFAULT '\u53d6\u6d88\u672c\u6b21',\n        created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,\n        FOREIGN KEY (schedule_id) REFERENCES schedule_events(id) ON DELETE CASCADE,\n        UNIQUE(schedule_id, occurrence_start)\n      )",
  "CREATE TABLE IF NOT EXISTS financial_accounts (\n          id TEXT PRIMARY KEY NOT NULL,\n          name TEXT NOT NULL,\n          type TEXT NOT NULL DEFAULT '\u73b0\u91d1',\n          color TEXT NOT NULL DEFAULT '#76528b',\n          initial_balance REAL NOT NULL DEFAULT 0,\n          is_archived INTEGER NOT NULL DEFAULT 0,\n          created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,\n          updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP\n        )",
  "CREATE TABLE IF NOT EXISTS side_hustle_clients (\n          id TEXT PRIMARY KEY NOT NULL,\n          name TEXT NOT NULL,\n          contact TEXT NOT NULL DEFAULT '',\n          payment_habit TEXT NOT NULL DEFAULT '',\n          note TEXT NOT NULL DEFAULT '',\n          next_follow_up_at TEXT,\n          created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,\n          updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP\n        )",
  "CREATE TABLE IF NOT EXISTS side_hustle_projects (\n          id TEXT PRIMARY KEY NOT NULL,\n          title TEXT NOT NULL,\n          kind TEXT NOT NULL DEFAULT '\u517c\u804c',\n          client_id TEXT,\n          billing_mode TEXT NOT NULL DEFAULT '\u6309\u5c0f\u65f6',\n          unit_rate REAL NOT NULL DEFAULT 0,\n          settlement_cycle TEXT NOT NULL DEFAULT '\u6bcf\u6b21\u7ed3\u675f',\n          status TEXT NOT NULL DEFAULT '\u8fdb\u884c\u4e2d',\n          income_target REAL NOT NULL DEFAULT 0,\n          start_at TEXT,\n          note TEXT NOT NULL DEFAULT '',\n          color TEXT NOT NULL DEFAULT '#477c6a',\n          created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,\n          updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,\n          FOREIGN KEY (client_id) REFERENCES side_hustle_clients(id) ON DELETE SET NULL\n        )",
  "CREATE TABLE IF NOT EXISTS work_sessions (\n          id TEXT PRIMARY KEY NOT NULL,\n          project_id TEXT NOT NULL,\n          schedule_id TEXT,\n          started_at TEXT NOT NULL,\n          ended_at TEXT,\n          minutes INTEGER NOT NULL DEFAULT 0,\n          hidden_minutes INTEGER NOT NULL DEFAULT 0,\n          paused_at TEXT,\n          paused_minutes INTEGER NOT NULL DEFAULT 0,\n          work_content TEXT NOT NULL DEFAULT '',\n          result TEXT NOT NULL DEFAULT '',\n          place TEXT NOT NULL DEFAULT '',\n          expected_income REAL NOT NULL DEFAULT 0,\n          cost REAL NOT NULL DEFAULT 0,\n          feeling TEXT NOT NULL DEFAULT '',\n          status TEXT NOT NULL DEFAULT '\u8fdb\u884c\u4e2d',\n          life_event_id TEXT,\n          created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,\n          updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,\n          FOREIGN KEY (project_id) REFERENCES side_hustle_projects(id) ON DELETE CASCADE,\n          FOREIGN KEY (life_event_id) REFERENCES life_events(id) ON DELETE SET NULL\n        )",
  "CREATE TABLE IF NOT EXISTS receivables (\n          id TEXT PRIMARY KEY NOT NULL,\n          project_id TEXT NOT NULL,\n          client_id TEXT,\n          work_session_id TEXT,\n          amount_due REAL NOT NULL DEFAULT 0,\n          amount_received REAL NOT NULL DEFAULT 0,\n          due_at TEXT,\n          status TEXT NOT NULL DEFAULT '\u5f85\u7ed3\u7b97',\n          note TEXT NOT NULL DEFAULT '',\n          created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,\n          updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,\n          FOREIGN KEY (project_id) REFERENCES side_hustle_projects(id) ON DELETE CASCADE,\n          FOREIGN KEY (client_id) REFERENCES side_hustle_clients(id) ON DELETE SET NULL,\n          FOREIGN KEY (work_session_id) REFERENCES work_sessions(id) ON DELETE SET NULL\n        )",
  "CREATE TABLE IF NOT EXISTS finance_transactions (\n          id TEXT PRIMARY KEY NOT NULL,\n          type TEXT NOT NULL DEFAULT '\u652f\u51fa',\n          amount REAL NOT NULL,\n          category TEXT NOT NULL DEFAULT '\u5176\u4ed6',\n          account_id TEXT,\n          transfer_account_id TEXT,\n          project TEXT NOT NULL DEFAULT '',\n          side_hustle_project_id TEXT,\n          work_session_id TEXT,\n          receivable_id TEXT,\n          related_transaction_id TEXT,\n          split_group_id TEXT,\n          recurring_transaction_id TEXT,\n          occurred_at TEXT NOT NULL,\n          note TEXT NOT NULL DEFAULT '',\n          is_private INTEGER NOT NULL DEFAULT 1,\n          deleted_at TEXT,\n          created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,\n          updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,\n          FOREIGN KEY (account_id) REFERENCES financial_accounts(id) ON DELETE SET NULL,\n          FOREIGN KEY (transfer_account_id) REFERENCES financial_accounts(id) ON DELETE SET NULL,\n          FOREIGN KEY (side_hustle_project_id) REFERENCES side_hustle_projects(id) ON DELETE SET NULL,\n          FOREIGN KEY (work_session_id) REFERENCES work_sessions(id) ON DELETE SET NULL,\n          FOREIGN KEY (receivable_id) REFERENCES receivables(id) ON DELETE SET NULL\n        )",
  "CREATE TABLE IF NOT EXISTS settlements (\n          id TEXT PRIMARY KEY NOT NULL,\n          receivable_id TEXT NOT NULL,\n          account_id TEXT,\n          transaction_id TEXT,\n          amount REAL NOT NULL,\n          received_at TEXT NOT NULL,\n          note TEXT NOT NULL DEFAULT '',\n          created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,\n          FOREIGN KEY (receivable_id) REFERENCES receivables(id) ON DELETE CASCADE,\n          FOREIGN KEY (account_id) REFERENCES financial_accounts(id) ON DELETE SET NULL,\n          FOREIGN KEY (transaction_id) REFERENCES finance_transactions(id) ON DELETE SET NULL\n        )",
  "CREATE TABLE IF NOT EXISTS life_event_versions (\n        id TEXT PRIMARY KEY NOT NULL,\n        event_id TEXT NOT NULL,\n        revision INTEGER NOT NULL,\n        snapshot_json TEXT NOT NULL DEFAULT '{}',\n        change_note TEXT NOT NULL DEFAULT '',\n        device_id TEXT NOT NULL DEFAULT '',\n        created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,\n        FOREIGN KEY (event_id) REFERENCES life_events(id) ON DELETE CASCADE\n      )"
];
export function database(legacy = true) {
  const sqlite = new DatabaseSync(":memory:");
  sqlite.exec("PRAGMA foreign_keys=ON");
  if (legacy) for (const schema of schemas) sqlite.exec(schema);
  const DB = {
    sqlite, beforeBatch: null,
    prepare(sql) {
      const stmt = {
        sql, values: [],
        bind(...values) { return { ...this, values }; },
        async first() { return sqlite.prepare(this.sql).get(...this.values) ?? null; },
        async all() { return { success: true, results: sqlite.prepare(this.sql).all(...this.values).map(row => ({ ...row })) }; },
        async run() {
          const result = sqlite.prepare(this.sql).run(...this.values);
          return { success: true, meta: { changes: Number(result.changes) } };
        },
      };
      return stmt;
    },
    async batch(statements) {
      if (this.beforeBatch) { const hook = this.beforeBatch; this.beforeBatch = null; hook(sqlite); }
      sqlite.exec("BEGIN IMMEDIATE");
      try {
        const results = statements.map(item => {
          if (item.values.length > 100) throw new Error("D1 binding limit exceeded");
          const prepared = sqlite.prepare(item.sql);
          // Fixtures use plain SELECT reads and WITH ... INSERT transaction guards.
          if (/^\s*SELECT\b/i.test(item.sql)) return { success: true, results: prepared.all(...item.values).map(row => ({ ...row })) };
          const result = prepared.run(...item.values);
          return { success: true, results: [], meta: { changes: Number(result.changes) } };
        });
        sqlite.exec("COMMIT");
        return results;
      } catch (error) { sqlite.exec("ROLLBACK"); throw error; }
    },
  };
  return DB;
}
export function count(DB, table) { return Number(DB.sqlite.prepare("SELECT count(*) AS n FROM " + table).get().n); }
